apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: challenge-1
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 1m }
  selector:
    matchLabels:
      app: challenge-1
  template:
    metadata:
      labels:
        app: challenge-1
    spec:
      containers:
        - name: challenge-1
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
